services:
  database:
    image: mysql:8.0.28
    container_name: database
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: backend_database
      MYSQL_USER: christian
      MYSQL_PASSWORD: 1234567890
      allowPublicKeyRetrieval: true
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - default
  backend:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: backend-template-nestjs
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_USERNAME: christian
      DB_PASSWORD: 1234567890
      DB_NAME: backend_database
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - default

volumes:
  mysql-data:
